### ISSUE TITLE
Width of one-third inputs are wrong when errored on mobile

### ISSUE THREAD

**Issue by Garconis** [Surbma/surbma-divi-gravity-forms#1]
It looks like, when Gravity Forms starts to stack the inputs (640px and below), the 1/3 width inputs have the wrong width, when they have an error. This is due your CSS of: 

`body .gform_wrapper .top_label li.gfield.gfield_error.gf_left_third, body .gform_wrapper .top_label li.gfield.gfield_error.gf_middle_third, body .gform_wrapper .top_label li.gfield.gfield_error.gf_right_third {
	width: 32%;
}`

That styling should only occur at 641px and above.

**Comment by Surbma** [comment]
Thank you for letting me know this. It was an inherited code, that was not deleted yet. Fix is coming.
