### ISSUE TITLE
Margin issue on errors

### ISSUE THREAD

**Issue by Garconis** [Surbma/surbma-divi-gravity-forms#3]
Your plugin adds

`body .gform_wrapper li.gfield.gfield_error.gfield_contains_required {
	margin: 0!important;
}`

However, this causes certain inputs to lose their necessary side margins.

2 column version:
[![https://gyazo.com/4a7a59353f8d8e21e6abc204095c20c9](https://gyazo.com/4a7a59353f8d8e21e6abc204095c20c9/raw)](https://gyazo.com/4a7a59353f8d8e21e6abc204095c20c9)

3 column version:
[![https://gyazo.com/27c78a75d02d57553653a24faa7ca254](https://gyazo.com/27c78a75d02d57553653a24faa7ca254/raw)](https://gyazo.com/27c78a75d02d57553653a24faa7ca254)

Perhaps that should only remove the top and bottom margins. I encourage you to further test styling and errors, using 2 and 3 column layouts.

Very helpful plugin so far though!

**Comment by Garconis** [comment]
Hoping this can get fixed soon. Errors don't look too good. :(

**Comment by Surbma** [comment]
I'm really thankful for all your bug reports @Garconis! I have fixed this issue and pushed the new version to the WP repo. Update is available in your admin soon.

Thank you again!
