### ISSUE TITLE
Font-family issue

### ISSUE THREAD

**Issue by Garconis** [Surbma/surbma-divi-gravity-forms#4]
Your internal CSS of `surbma-divi-gravity-forms-styles-inline-css`

`font-family: 'inherit', ;`

The word inherit shouldn't be in quotes, and also there is an extra comma before the closing semi-colon.

**Comment by Surbma** [comment]
Thank you for the report! It is coming from Divi settings, I can't do anything about it. I just add the same font family to Gravity Forms, that your actual Divi configuration uses.

Please report this bug to Elegant Themes, they need to consider and fix this problem.

**Comment by Garconis** [comment]
Upon further investigation, this seems to be coming from your plugin in some form.

```
<style id='surbma-divi-gravity-forms-styles-inline-css' type='text/css'>
body .gform_wrapper .gform_footer input.button,body .gform_wrapper .gform_page_footer input.button,body div.form_saved_message div.form_saved_message_emailform form input[type=submit]{background-color:#fff;color:#32a709;border-width:2px;border-color:#32a709;border-radius:3px;font-family: 'inherit', sans-serif;font-size:20px;letter-spacing:0px;}body .gform_wrapper .gform_footer input.button:hover,body .gform_wrapper .gform_page_footer input.button:hover,body div.form_saved_message div.form_saved_message_emailform form input[type=submit]:hover{background-color:rgba(0,0,0,.05);color:#32a709;border-color:transparent;border-radius:3px;letter-spacing:0px;}
</style>
```

If not, perhaps you can just add a class to your plugin, to fix the `font-family: 'inherit', sans-serif;` bit? It should only be `font-family: inherit;`

**Comment by Surbma** [comment]
Garconis, as I have already told you, these values are coming from Divi settings. I don't give it any value in my code. I just add the button font styles to Gravity Forms to follow your settings.
